### ISSUE TITLE
foreachasync problem on `npm install`

### ISSUE THREAD

**Issue by extempl** [coolaj86/node-walk#55]
npm ERR! notarget No compatible version found: foreachasync@'>=2.2.0 <2.3.0'
    npm ERR! notarget Valid install targets:
    npm ERR! notarget ["3.0.0","5.0.4","5.0.5"]
    npm ERR! notarget
    npm ERR! notarget This is most likely not a problem with npm itself.
    npm ERR! notarget In most cases you or one of your dependencies are requesting
    npm ERR! notarget a package version that doesn't exist.
    npm ERR! notarget
    npm ERR! notarget It was specified as a dependency of 'walk'
    npm ERR! notarget

On Windows it ends with no errors and installs 2.2.1 version which does not works.

I do not understand what is going here and why, but I think, `"foreachasync": "^3.0.0"` -> `"foreachasync": "3.0.0"` or `"foreachasync": "3.0.x"` should fix the problem.

**Comment by extempl** [comment]
`npm install walk` installs `foreachasync@3.0.0`, but `npm install` with `"walk": "^2.3.9",` in dependencies of `package.json` crashes with the error above. For some reason it takes old dependency `~2.2`. How this could be?

**Comment by Avcajaraville** [comment]
Same for me, its breaking my builds :(

**Comment by NetOperatorWibby** [comment]
Whenever I install a new npm module into my project, `foreachasync` gets updated and the resulting error when running my app results in:

```
/project/node_modules/hbs-utils/node_modules/walk/lib/walk.js:153
      forEachAsync(me._wcurfiles, me._wFilesHandler, me).then(me._wPostFilesHandler);
      ^

TypeError: forEachAsync is not a function
    at Walker._wReadFiles (/project/node_modules/hbs-utils/node_modules/walk/lib/walk.js:153:7)
    at Walker._wReaddirHandler (/project/node_modules/hbs-utils/node_modules/walk/lib/walk.js:166:10)
    at /project/node_modules/hbs-utils/node_modules/walk/lib/walk.js:225:10
    at FSReqWrap.oncomplete (fs.js:123:15)

```

**Comment by tuck182** [comment]
To anyone else who runs across this: I believe this _may_ be due to the naming change in forEachAsync between 2.x (forEachAsync) and 3.x (foreachasync), and case-insensitive filesystems. Our team was getting this error on OS-X but not Linux. We fixed it by adding `foreachasync@^3.0.0` as an explicit project dependency alongside `hbs@~4.0.1`.
